version: "3.8"

services:
  web: &web
    tty: true
    stdin_open: true
    image: minesweeper:dev
    build:
      context: .
    environment:
      REDIS_HOST: redis
    command: sh docker/start.sh
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    env_file:
      - web.env
    depends_on:
      - redis
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: minesweeper
    ports:
      - "3333:3306"
    volumes:
      - ./db_volume/mysql_data:/var/lib/mysql
      - ./db_volume/mysql_config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

  redis:
    image: redis:7.0-alpine
    ports:
      - 6380:6380

  sidekiq: &sidekiq
    <<: *web
    ports:
      - "3001:3000"
    depends_on:
      - redis
    build: .
    command: bash -c "bundle exec sidekiq"
    volumes:
      - .:/app
    env_file:
      - web.env
